parameters:
#    shopify_ninja_shopify.example.class: ShopifyNinja\ShopifyBundle\Example

services:
#    shopify_ninja_shopify.example:
#        class: %shopify_ninja_shopify.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
