<?php

namespace ShopifyNinja\ShopifyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
	public function getImagesForProduct($ids, $array = false) {
		$queryBuilder = $this->getEntityManager()->createQueryBuilder();

		$queryBuilder->select(array('i','p'))
			->from('ShopifyNinjaShopifyBundle:Image', 'i')
			->leftJoin('i.product', 'p')
			->where('p.id IN (:ids)')
			->setParameter('ids', $ids);

		if ($array) {
			return $queryBuilder->getQuery()->getArrayResult();
		}

		return $queryBuilder->getQuery()->getResult();

	}
}
