<?php

namespace ShopifyNinja\ShopifyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
	public function getImagesForProduct($ids, $array = false) {
		$queryBuilder = $this->getEntityManager()->createQueryBuilder();

		$queryBuilder->select(array('i'))
			->from('ShopifyNinjaShopifyBundle:Image', 'i')
			->where($queryBuilder->expr()->in('i.product', $ids));
			
		if ($array) {
			return $queryBuilder->getQuery()->getArrayResult();
		}

		return $queryBuilder->getQuery()->getResult();

	}
}
