<?php

namespace ShopifyNinja\ShopifyBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ShopifyNinja\ShopifyBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
	public function getAllProducts($array = false) {
		$queryBuilder = $this->getEntityManager()->createQueryBuilder();

		$queryBuilder->select(array('p'))
			->from('ShopifyNinjaShopifyBundle:Product', 'p');

		if ($array) {
			return $queryBuilder->getQuery()->getArrayResult();
		}

		return $queryBuilder->getQuery()->getResult();

	}
}
