<?php

namespace ShopifyNinja\ShopifyBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ShopifyNinja\ShopifyBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
	public function getAllProducts($array = false) {
		$queryBuilder = $this->getEntityManager()->createQueryBuilder();

		$queryBuilder->select(array('p'))
			->from('ShopifyNinjaShopifyBundle:Product', 'p');

		if ($array) {
			return $queryBuilder->getQuery()->getArrayResult();
		}

		return $queryBuilder->getQuery()->getResult();

	}

	public function getById($id){
		$query = $this->createQueryBuilder('p')
			->select('p')
			->where('p.id = :id')
			->setParameter('id', $id)
			->getQuery();

		return $queryBuilder->getQuery()->getOneOrNullResult();

	}

	public function getByIds($ids){
		$query = $this->createQueryBuilder('p')
			->select('p')
			->where('p.id IN (:ids)')
			->setParameter('ids', $ids)
			->getQuery();

		try {
			return $query->getResult();
		} catch(\Doctrine\Orm\NoResultException $e) {
			return null;
		}
	}
}
