<?php

namespace ShopifyNinja\ShopifyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShopifyOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopifyOptionRepository extends EntityRepository
{
}
